apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec: 
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - name: cm-volume
      mountPath: /etc/config/cm
    - name: sec-volume
      mountPath: /etc/config/sec
  volumes:
  - name: cm-volume
    configMap:
      name: my-configmap
  - name: sec-volume
    secret:
      secretName: my-secret
