apiVersion: v1
kind: Pod
metadata:
  name: liveness-nginx-pod
spec:
  containers:
  - name: nginxpod
    image: nginx:1.19.1
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
