apiVersion: v1
kind: Pod
metadata:
  name: rediness-pod
spec:
  containers:
  - name: nginxpod
    image: nginx:1.19.1
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
