apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Success! > /output/success.txt']
    volumeMounts:
    - name: my-vol
      mountPath: /output
  volumes:
  - name: my-vol
    hostPath: 
      path: /var/voldata

