apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo Success! > /output/success.txt; sleep 5; done']
    volumeMounts:
    - name: my-vol
      mountPath: /output
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'while true; do cat /input/success.txt; sleep 5; done']
    volumeMounts:
    - name: my-vol
      mountPath: /input
  volumes:
  - name: my-vol
    emptyDir: {}
