# login to worker node
# create static file manifest file  (/etc/kubernetes/manifests)

---
apiVersion: v1
kind: Pod
metadata:
  name: static-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1

